#use_frameworks!

platform :ios, '8.0'

target 'LNBusinessCommonComponent_Example' do
  pod 'LNBusinessCommonComponent', :path => '../'

  target 'LNBusinessCommonComponent_Tests' do
    inherit! :search_paths

    
  end
end
